"use server";

import { createAdminClient } from "@/lib/supabase/admin";
import { createClient, createClientForSchema } from "@/lib/supabase/server";
import { redirect } from "@/i18n/navigation";
import { defaultRouteForRole } from "@/lib/auth";
import { clientIp, consume, LIMITS, retryMessage } from "@/lib/rate-limit";
import { getTenant } from "@/lib/tenant";
import { tenantClaimFromToken } from "@/lib/tenant-claim";
import { DEMO_ACCOUNTS, getDemoStatus, isDemoAccountKey, isFlagshipDemo } from "@/lib/demo";
import type { Role } from "@/lib/supabase/types";

// Passwordless persona switching for the flagship demo.
//
// THIS FILE ISSUES SESSIONS WITHOUT A CREDENTIAL. There is no password
// anywhere in it, by design — a demo whose passwords are printed on the
// login page is a published credential, and one that is emailed to
// prospects is a support burden. So the trust is moved: instead of
// proving who you are, you prove nothing, and the endpoint proves that
// the only thing it can possibly do is sign you into one of six seeded
// accounts on one specific showroom.
//
// That makes the four guards below the entire security boundary. A
// Server Action is a public HTTP endpoint reachable by direct POST from
// an allow-listed origin (see next.config.ts), so none of them may be
// left to the UI:
//
//   1. `key` is an opaque allowlist member — never an email address, so
//      the reachable account set is fixed in demo-accounts.ts at build
//      time. auth.users is shared with A-Star and Calendar on one GoTrue
//      instance, so an email parameter here would be a session oracle for
//      other products' real accounts.
//   2. The request is for the flagship's own hostname. On a licensed
//      client's subdomain this action does nothing at all.
//   3. The demo is switched on. The kill switch has to bind the action,
//      not just the page that renders the buttons.
//   4. Per-IP throttle, so the endpoint cannot be used to mint sessions
//      in bulk (each call is two GoTrue round trips).
//
// Even if all four were somehow bypassed, the blast radius is a session
// on a seeded demo showroom whose data is regenerated by a script. There
// is nothing real behind it.

export type DemoSwitchState =
  | { error: "denied" | "demoOff" | "failed" | "wrongTenant" | "throttled"; message?: string }
  | undefined;

export async function switchDemoRole(
  locale: string,
  key: string
): Promise<DemoSwitchState> {
  // GUARD 1 — allowlist. hasOwnProperty-based, so prototype keys such as
  // "constructor" cannot slip through into the lookup below.
  if (!isDemoAccountKey(key)) return { error: "denied" };

  // GUARD 2 — flagship only. Not a UI concern: without this, POSTing to
  // this action from a licensed showroom's subdomain would try to sign
  // the caller into the demo's accounts. The claim cross-check further
  // down would catch it, but refusing before touching GoTrue at all is
  // the honest place to say "this feature does not exist here".
  const tenant = await getTenant();
  if (!tenant || !isFlagshipDemo(tenant) || tenant.status === "suspended") {
    return { error: "denied" };
  }

  // GUARD 3 — the kill switch.
  const status = await getDemoStatus();
  if (!status.enabled) return { error: "demoOff" };

  // GUARD 4 — throttle. Per IP only: there is no account to protect here
  // (the six personas are meant to be shared), so the per-email bucket
  // the login action carries would just penalise a busy demo.
  const ip = await clientIp();
  const throttle = await consume(`demo-switch:ip:${ip}`, LIMITS.demoSwitch);
  if (!throttle.allowed) {
    return { error: "throttled", message: await retryMessage(throttle.retryAfter) };
  }

  const account = DEMO_ACCOUNTS[key];
  const supabase = await createClient();

  // Drop whatever session is already here before minting the next one,
  // so a failure halfway through leaves the visitor signed out rather
  // than still signed in as the previous persona.
  //
  // SCOPE MUST BE LOCAL. The default is global, which revokes every
  // refresh token belonging to the account. These six accounts are shared
  // by every visitor to the demo at once, so a global sign-out would
  // eject every other prospect currently browsing as that persona each
  // time somebody clicked a different button. Local clears this browser's
  // cookies and nothing else, which is exactly the intent.
  await supabase.auth.signOut({ scope: "local" });

  // The mechanism, in two steps and no passwords:
  //
  //   generateLink() asks GoTrue for the magic link it would normally
  //   have emailed, and hands back its `hashed_token` instead of sending
  //   anything. Service-role only, so it is unreachable from a browser.
  //
  //   verifyOtp() then redeems that token on the SSR client, which is the
  //   one wired to the cookie jar — so the resulting session is written
  //   as cookies on this response, exactly as a password sign-in would
  //   have written it. Nothing is emailed, and the token never leaves the
  //   server: it is created and spent inside this one request.
  //
  // `type: "magiclink"` is what the installed @supabase/auth-js 2.111
  // accepts on both sides (GenerateInviteOrMagiclinkParams, and
  // VerifyTokenHashParams via EmailOtpType) — "email" is for the OTP-code
  // flow, which is not what generateLink's hashed_token is.
  const admin = createAdminClient();
  const { data: link, error: linkError } = await admin.auth.admin.generateLink({
    type: "magiclink",
    email: account.email,
  });

  const tokenHash = link?.properties?.hashed_token;
  if (linkError || !tokenHash) {
    // Almost always "the seed has not been run against this project", so
    // log the key rather than the address — the address is derivable and
    // the key is what a reader needs to find the row.
    console.error("[demo] generateLink failed", { key, error: linkError });
    return { error: "failed" };
  }

  const { data: verified, error: verifyError } = await supabase.auth.verifyOtp({
    type: "magiclink",
    token_hash: tokenHash,
  });

  if (verifyError || !verified.session) {
    console.error("[demo] verifyOtp failed", { key, error: verifyError });
    return { error: "failed" };
  }

  // The same cross-check the login action makes, for the same reason: the
  // account belongs to one showroom and the hostname belongs to one
  // showroom, and a session may only exist where those agree.
  //
  // It is not redundant just because the emails are hard-coded. What this
  // catches is a misconfigured *database*: a demo account whose
  // platform.tenant_users membership points somewhere other than t_felix,
  // or a Supabase project where the access token hook is not registered
  // at all (no claim). Waving either through would put a session with no
  // tenant role — or the wrong one — inside the flagship's shell.
  const claim = tenantClaimFromToken(verified.session.access_token);
  if (!claim || claim.slug !== tenant.slug || claim.schema !== tenant.schema_name) {
    await supabase.auth.signOut({ scope: "local" });
    console.error("[demo] persona session did not match this showroom", { key, claim });
    return { error: "wrongTenant" };
  }

  // Read the role through a client pinned to the claim's schema. The
  // memoized `supabase` above was built before this session existed, so
  // it carries no schema of its own — querying profiles with it would hit
  // `public`. The seeded role on DEMO_ACCOUNTS is only the fallback; the
  // showroom's own row is the authority, so a persona whose role was
  // changed in the database lands on the right dashboard anyway.
  const scoped = await createClientForSchema(claim.schema);
  const { data: profile } = await scoped
    .from("profiles")
    .select("role")
    .eq("id", verified.session.user.id)
    .maybeSingle();

  const role = ((profile as { role?: Role } | null)?.role as Role) || account.role;

  // redirect() throws NEXT_REDIRECT — it must stay outside any try/catch.
  redirect({ href: defaultRouteForRole(role), locale });
}
